FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV MONGODB_URI="mongodb://localhost:27017/dummy_build_db"
ENV NEXTAUTH_SECRET="dummy_build_secret_key_123456789"
ENV NEXTAUTH_URL="http://localhost:3000"

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
